import re
from typing import Optional, Dict, Any


def extract_metadata_from_recipe(recipe_text: str) -> Dict[str, Any]:
    """
    Extract metadata from the recipe text
    
    Looks for the METADATA section at the end of the recipe
    and extracts structured information
    
    Returns a dict with:
        - cuisine: str or None
        - time_minutes: int or None
        - effort_level: str or None
        - calories_per_serving: int or None
    """
    metadata = {
        "cuisine": None,
        "time_minutes": None,
        "effort_level": None,
        "calories_per_serving": None
    }
    
    # Look for metadata section
    metadata_match = re.search(
        r'---\s*METADATA:\s*(.*?)\s*---',
        recipe_text,
        re.DOTALL | re.IGNORECASE
    )
    
    if not metadata_match:
        return metadata
    
    metadata_text = metadata_match.group(1)
    
    # Extract cuisine
    cuisine_match = re.search(
        r'Cuisine:\s*(.+)',
        metadata_text,
        re.IGNORECASE
    )
    if cuisine_match:
        metadata["cuisine"] = cuisine_match.group(1).strip()
    
    # Extract time (convert to minutes)
    time_match = re.search(
        r'Total Time:\s*(\d+)',
        metadata_text,
        re.IGNORECASE
    )
    if time_match:
        metadata["time_minutes"] = int(time_match.group(1))
    
    # Extract effort
    effort_match = re.search(
        r'Effort:\s*(Low|Medium|High)',
        metadata_text,
        re.IGNORECASE
    )
    if effort_match:
        metadata["effort_level"] = effort_match.group(1).capitalize()
    
    # Extract calories
    calories_match = re.search(
        r'Calories:\s*(\d+)',
        metadata_text,
        re.IGNORECASE
    )
    if calories_match:
        metadata["calories_per_serving"] = int(calories_match.group(1))
    
    return metadata


def format_recipe_for_download(
    recipe_text: str,
    recipe_metadata: Dict[str, Any]
) -> str:
    """
    Format a recipe for text file download
    
    Args:
        recipe_text: The recipe content from LLM
        recipe_metadata: Metadata dict with creation info
    
    Returns:
        Formatted text for download
    """
    header_parts = [
        "=" * 60,
        "Elzar Recipe Generator 🌶️",
        "BAM! Let's make cooking delicious!",
        "=" * 60,
        "",
        f"Generated: {recipe_metadata.get('created_at', 'Unknown')}",
    ]
    
    if recipe_metadata.get("cuisine"):
        header_parts.append(f"Cuisine: {recipe_metadata['cuisine']}")
    
    if recipe_metadata.get("time_minutes"):
        header_parts.append(f"Time: {recipe_metadata['time_minutes']} minutes")
    
    if recipe_metadata.get("effort_level"):
        header_parts.append(f"Effort: {recipe_metadata['effort_level']}")
    
    if recipe_metadata.get("calories_per_serving"):
        header_parts.append(
            f"Calories: {recipe_metadata['calories_per_serving']} per serving"
        )
    
    if recipe_metadata.get("active_profiles"):
        profiles = recipe_metadata["active_profiles"]
        if profiles:
            header_parts.append(f"Dietary Profiles: {', '.join(profiles)}")
    
    header_parts.extend([
        "",
        "=" * 60,
        "",
    ])
    
    footer_parts = [
        "",
        "",
        "=" * 60,
        "Generated by Elzar - Grocy Recipe Generator",
        "https://github.com/your-repo",
        "=" * 60
    ]
    
    return "\n".join(header_parts) + recipe_text + "\n".join(footer_parts)

